name: SAP Project Piper CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  piper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Piper Maven Build
      run: |
        docker run --rm \
          -v "$PWD":/workspace \
          -v "$HOME/.m2":/root/.m2 \
          -w /workspace \
          ppiper/docker-image:latest \
          piper mavenBuild


    - name: Docker Login (for Push)
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Run Docker Build + Push with Piper
      run: |
        docker run --rm \
          -v "$PWD":/workspace \
          -v "$HOME/.docker":/root/.docker \
          -w /workspace \
          ppiper/docker-image:latest \
          piper dockerBuild
